# NAME: AppleService
# Link1: https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Apple/Apple.yaml
# Link2: https://github.com/DivineEngine/Profiles/blob/master/Clash/RuleSet/Extra/Apple/Apple.yaml
# update:2021-07-30
payload:
  - DOMAIN,apple.comscoreresearch.com
  - DOMAIN-SUFFIX,aaplimg.com
  - DOMAIN-SUFFIX,akadns.net
  - DOMAIN-SUFFIX,apple-cloudkit.com
  - DOMAIN-SUFFIX,apple-dns.net
  - DOMAIN-SUFFIX,apple.co
  - DOMAIN-SUFFIX,apple.com
  - DOMAIN-SUFFIX,apple.com.cn
  - DOMAIN-SUFFIX,appsto.re
  - DOMAIN-SUFFIX,appstore.com
  - DOMAIN-SUFFIX,cdn-apple.com
  - DOMAIN-SUFFIX,crashlytics.com
  - DOMAIN-SUFFIX,digicert.com
  - DOMAIN-SUFFIX,icloud.com
  - DOMAIN-SUFFIX,icloud.com.cn
  - DOMAIN-SUFFIX,icloud-content.com
  - DOMAIN-SUFFIX,itunes.com
  - DOMAIN-SUFFIX,me.com
  - DOMAIN-SUFFIX,mzstatic.com
  - DOMAIN-SUFFIX,store.apple.com.edgekey.net
  - DOMAIN-SUFFIX,www.apple.com.edgekey.net
  - DOMAIN-KEYWORD,icloud.com.akadns.net
  - DOMAIN-KEYWORD,apple.com.akadns.net
  - DOMAIN-KEYWORD,testflight
  - IP-CIDR,17.0.0.0/8,no-resolve
  - IP-CIDR,63.92.224.0/19,no-resolve
  - IP-CIDR,65.199.22.0/23,no-resolve
  - IP-CIDR,139.178.128.0/18,no-resolve
  - IP-CIDR,144.178.0.0/19,no-resolve
  - IP-CIDR,192.35.50.0/24,no-resolve
  - IP-CIDR,198.183.17.0/24,no-resolve
  - IP-CIDR,205.180.175.0/24,no-resolve
